title: Camilo J. Gomez
description: > # this means to ignore newlines until "baseurl:"
  Personal web page of Camilo Gomez.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cjgomez.cl" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Camilo J. Gomez
tagline: Persona
about-description: Computer Engineer and M. Sc. in Computer Science Student at University of Chile. # Add Discription
pic: camilo-hd.png  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: cjgomez@dcc.uchile.cl # Add your Email address
# phone: 044 825 5523 # Add your Phone number
website: cjgomez.cl # Add your website, do not add http://
linkedin: camilo-gómez-núñez-39848638/ # Add your Linkedin handle
github: camilog # Add your Github handle
twitter: '@milogomez__' # Add your Twitter handle

# Tracker
analytics: UA-86992080-1

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
